[package]
name = "z3_overworld_editor"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[profile.release.package."*"]
debug = false

[dependencies]
iced = { version= "0.13.1", features = ["canvas", "svg", "smol", "image", "advanced", "lazy"] }
iced_aw = { version = "0.12.0", default-features = false, features = ["number_input", "menu", "quad"] }
iced_fonts = { version = "0.2.1", features = ["bootstrap"] }
dark-light = "2.0.0"
directories = "6.0.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1"
anyhow = "1.0.98"
env_logger = "0.11.8"
rfd = "0.15.3"
json-pretty-compact = "0.1.2"
glob = "0.3.2"
hashbrown = "0.15.3"
itertools = "0.14.0"
png = "0.17.16"
notify = "8.0.0"
clap = { version = "4.5.38", features = ["derive"] }
heuristic-graph-coloring = "0.1.0"