use std::path::PathBuf;

use iced::Point;

use crate::state::{
    AnimatedTileGroup, AreaId, AreaPosition, CollisionType, ColorIdx, ColorRGB, ColorValue,
    DynamicTileTarget, DynamicTileType, DynamicTileVariant, Focus, Palette, PaletteId, PaletteIdx,
    PixelCoord, PixelTarget, Tile, TileBlock, TileCoord, TileIdx,
};

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum SelectionSource {
    Area(AreaPosition),
    Tileset,
    DynamicTiles {
        kind: DynamicTileType,
        variant: usize,
        target: DynamicTileTarget,
    },
}

#[derive(Debug, Clone)]
pub enum Message {
    Nothing,
    Event(iced::Event),
    Focus(Focus),
    WindowClose(iced::window::Id),
    SaveProject,
    OpenProject,
    ModifiedReload,
    RebuildProjectDialogue,
    RebuildProject,
    ProjectOpened(Option<PathBuf>),
    SettingsDialogue,
    OpenDynamicTiles,
    CloseDynamicTiles,
    SelectDynamicTileType(DynamicTileType),
    SelectDynamicTileFrame {
        variant: usize,
        frame: usize,
    },
    AddDynamicTileVariant,
    DeleteDynamicTileVariant(usize),
    SetDynamicTileVariants {
        kind: DynamicTileType,
        variants: Vec<DynamicTileVariant>,
    },
    DynamicTileBrush {
        kind: DynamicTileType,
        variant: usize,
        target: DynamicTileTarget,
        coords: Point<TileCoord>,
        selection: TileBlock,
    },
    HelpDialogue,
    SetPixelSize(f32),
    SetGridAlpha(f32),
    CloseDialogue,
    ImportDialogue,
    ImportConfirm(Option<PathBuf>),
    ImportROMProgress,
    ImportROM,
    SelectPalette(String),
    AddPaletteDialogue,
    SetAddPaletteName(String),
    SetAddPaletteID(PaletteId),
    AddPalette {
        name: String,
        id: PaletteId,
    },
    DeletePaletteDialogue,
    DeletePalette(PaletteId),
    RestorePalette(Palette),
    AnimatedTilesDialogue,
    SelectAnimatedGroup(TileIdx),
    SelectAnimatedTile {
        base_tile: TileIdx,
        frame: usize,
        tile: usize,
    },
    AddAnimatedTileGroup {
        palette_id: PaletteId,
        group: AnimatedTileGroup,
    },
    DeleteAnimatedTileGroup {
        palette_id: PaletteId,
        base_tile: TileIdx,
    },
    SetAnimatedTileGroup {
        palette_id: PaletteId,
        base_tile: TileIdx,
        group: AnimatedTileGroup,
    },
    SetAnimatedFrameCount {
        palette_id: PaletteId,
        base_tile: TileIdx,
        frame_count: u16,
    },
    SetAnimatedFrameHold {
        palette_id: PaletteId,
        base_tile: TileIdx,
        frame_hold: u16,
    },
    SetAnimatedPhaseOffset {
        palette_id: PaletteId,
        base_tile: TileIdx,
        phase_offset: u16,
    },
    RenamePaletteDialogue,
    SetRenamePaletteName(String),
    RenamePalette {
        id: PaletteId,
        name: String,
    },
    HideModal,
    SelectColor(PaletteIdx, ColorIdx),
    BrushColor {
        palette_id: PaletteId,
        color_idx: ColorIdx,
        color: ColorRGB,
    },
    ChangeRed(ColorValue),
    ChangeGreen(ColorValue),
    ChangeBlue(ColorValue),
    AddTileRow(PaletteId),
    DeleteTileRow(PaletteId),
    RestoreTileRow(PaletteId, Vec<Tile>),
    SetTilePriority {
        palette_id: PaletteId,
        tile_idx: TileIdx,
        priority: bool,
    },
    SetTileCollision {
        palette_id: PaletteId,
        tile_idx: TileIdx,
        collision: CollisionType,
    },
    SetTileHFlippable {
        palette_id: PaletteId,
        tile_idx: TileIdx,
        h_flippable: bool,
    },
    SetTileVFlippable {
        palette_id: PaletteId,
        tile_idx: TileIdx,
        v_flippable: bool,
    },
    TilesetBrush {
        palette_id: PaletteId,
        coords: Point<TileCoord>,
        selected_gfx: Vec<Vec<Tile>>,
        tile_block: Option<TileBlock>,
    },
    SelectPixel(PixelTarget, PixelCoord, PixelCoord),
    BrushPixel {
        palette_id: PaletteId,
        target: PixelTarget,
        coords: Point<PixelCoord>,
        color_idx: ColorIdx,
    },
    SelectArea(AreaPosition, String),
    AddAreaDialogue,
    SetAddAreaName(String),
    SetAddAreaSizeX(u8),
    SetAddAreaSizeY(u8),
    AddArea {
        name: String,
        size: (u8, u8),
    },
    EditAreaDialogue,
    SetEditAreaName(String),
    EditArea {
        old_name: String,
        new_name: String,
    },
    EditAreaBGRed(ColorValue),
    EditAreaBGGreen(ColorValue),
    EditAreaBGBlue(ColorValue),
    EditAreaBGColor {
        area_id: AreaId,
        color: ColorRGB,
    },
    DeleteAreaDialogue,
    DeleteArea(String),
    SelectTheme(AreaPosition, String),
    AddThemeDialogue,
    SetAddThemeName(String),
    AddTheme(String),
    RenameThemeDialogue,
    SetRenameThemeName(String),
    RenameTheme {
        old_name: String,
        new_name: String,
    },
    DeleteThemeDialogue,
    DeleteTheme(String),
    HoverArea(Point<TileCoord>),
    HoverAreaEnd,
    StartTileSelection(Point<TileCoord>, SelectionSource),
    ProgressTileSelection(Point<TileCoord>),
    EndTileSelection(Point<TileCoord>),
    AreaBrush {
        position: AreaPosition,
        area_id: AreaId,
        coords: Point<TileCoord>,
        selection: TileBlock,
        palette_only: bool,
    },
    OpenTile {
        palette_id: PaletteId,
        tile_idx: TileIdx,
    },
    MovingTilesProgress {
        src_selection: TileBlock,
        dst_selection: TileBlock,
        check_reversible: bool,
    },
    MoveTiles {
        src_selection: TileBlock,
        dst_selection: TileBlock,
        check_reversible: bool,
    },
    MoveTilesConfirmDialogue {
        src_selection: TileBlock,
        dst_selection: TileBlock,
    },
}
